apiVersion: v1
kind: ServiceAccount
metadata:
  name: dmt-user
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-dmt-cm-view-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-dmt-cm-svc-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-dmt-cm-view-role
subjects:
  - kind: ServiceAccount
    name: dmt-user
    namespace: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: dmt
  name: dmt
  namespace: default
spec:
  ports:
    - name: http
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: dmt
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dmt
  name: dmt
  namespace: default
spec:
  replicas: 8
  selector:
    matchLabels:
      app: dmt
      type: dmt
  template:
    metadata:
      labels:
        app: dmt
        type: dmt
      namespace: default
    spec:
      serviceAccount: dmt-user
      serviceAccountName: dmt-user
      containers:
        - image: minio/dmt:latest
          imagePullPolicy: IfNotPresent
          name: dmt
          ports:
            - containerPort: 8443
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/dmt
              name: dmt-configuration-tls
      dnsPolicy: ClusterFirst
      nodeSelector:
        env: compute
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
        - name: dmt-configuration-tls
          projected:
            defaultMode: 420
            sources:
              - secret:
                  name: dmt-ca-cert
                  items:
                    - key: ca.crt
                      path: ca.crt
              - secret:
                  name: certificate-secrets-domain-1
                  items:
                    - key: tls.crt
                      path: tls/my-domain-one.com/public.crt
                    - key: tls.key
                      path: tls/my-domain-one.com/private.key
              - secret:
                  name: certificate-secrets-domain-2
                  items:
                    - key: tls.crt
                      path: tls/my-domain-two.com/public.crt
                    - key: tls.key
                      path: tls/my-domain-two.com/private.key
              - secret:
                  name: certificate-secrets-domain-3
                  items:
                    - key: tls.crt
                      path: tls/my-domain-three.com/public.crt
                    - key: tls.key
                      path: tls/my-domain-three.com/private.key
